num = int(input('Digite um número para ver sua tabuada: '))
print('---------------')
print('{} x  1 = {}\n{} x  2 = {}\n{} x  3 = {}\n{} x  4 = {}'.format(num, num, num, num*2, num, num*3, num, num*4))
print('{} x  5 = {}\n{} x  6 = {}\n{} x  7 = {}\n{} x  8 = {}'.format(num, num*5, num, num*6, num, num*7, num, num*8))
print('{} x  9 = {}\n{} x 10 = {}\n'.format(num, num*9, num, num*10), end='---------------')
